### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by spillz** [denilsonsa/gimp-palettes#10]
Are all of these palettes available under permissable open source/creative commons licenses?

**Comment by denilsonsa** [comment]
Well, I'm not a lawyer, but the licensing part isn't clear. Although I did the work to convert and organize all these palettes (and I'm fine releasing my part of the work as Public Domain), the palettes themselves were collected from many freely-available places on the web, and I'm not sure about their licenses.

But also… if people shared their palettes, I'm assuming they are fine with other people using their palettes. All I've done is repacking them into `*.gpl` format to be usable with most open-source tools. In any case, I left the credits for the sources of all the palettes.

(Closing because it was a question, and I replied to the best of my limited knowledge. Feel free to reopen if desired.)
